#pragma once

// From glfw3.h
#define POLAR_MOUSE_BUTTON_1         0
#define POLAR_MOUSE_BUTTON_2         1
#define POLAR_MOUSE_BUTTON_3         2
#define POLAR_MOUSE_BUTTON_4         3
#define POLAR_MOUSE_BUTTON_5         4
#define POLAR_MOUSE_BUTTON_6         5
#define POLAR_MOUSE_BUTTON_7         6
#define POLAR_MOUSE_BUTTON_8         7
#define POLAR_MOUSE_BUTTON_LAST      POLAR_MOUSE_BUTTON_8
#define POLAR_MOUSE_BUTTON_LEFT      POLAR_MOUSE_BUTTON_1
#define POLAR_MOUSE_BUTTON_RIGHT     POLAR_MOUSE_BUTTON_2
#define POLAR_MOUSE_BUTTON_MIDDLE    POLAR_MOUSE_BUTTON_3